server:
  port: 8080

spring:
  application:
    name: votacao
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/votacao_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9094
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
    consumer:
      group-id: votacao-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate

app:
  integration:
    user-info:
      # A URL de callback/integração para validar o CPF. 
      # Pode ser sobrescrita em qualquer ambiente injetando a variável APP_INTEGRATION_USER_INFO_URL
      url: ${APP_INTEGRATION_USER_INFO_URL:https://user-info.herokuapp.com/users}

resilience4j:
  circuitbreaker:
    instances:
      userInfo:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  retry:
    instances:
      userInfo:
        maxAttempts: 3
        waitDuration: 1s
